/*
3474. Lexicographically Smallest Generated String

You are given two strings, str1 and str2, of lengths n and m, respectively.

A string word of length n + m - 1 is defined to be generated by str1 and str2 if it satisfies the following conditions for each index 0 <= i <= n - 1:

If str1[i] == 'T', the substring of word with size m starting at index i is equal to str2, i.e., word[i..(i + m - 1)] == str2.
If str1[i] == 'F', the substring of word with size m starting at index i is not equal to str2, i.e., word[i..(i + m - 1)] != str2.
Return the lexicographically smallest possible string that can be generated by str1 and str2. If no string can be generated, return an empty string "".


Example 1:
    Input: str1 = "TFTF", str2 = "ab"
    Output: "ababa"
    Explanation:
        The table below represents the string "ababa"
        Index	T/F	Substring of length m
        0	'T'	"ab"
        1	'F'	"ba"
        2	'T'	"ab"
        3	'F'	"ba"
        The strings "ababa" and "ababb" can be generated by str1 and str2.

    Return "ababa" since it is the lexicographically smaller string.

Example 2:
    Input: str1 = "TFTF", str2 = "abc"
    Output: ""
    Explanation:
        No string that satisfies the conditions can be generated.

Example 3:
    Input: str1 = "F", str2 = "d"
    Output: "a"


Constraints:
    1 <= n == str1.length <= 10^4
    1 <= m == str2.length <= 500
    str1 consists only of 'T' or 'F'.
    str2 consists only of lowercase English characters.
*/

// Greedy Approach: TC: O(nm), SC:O(n+m)
class Solution {
public:
    string generateString(string str1, string str2) {
        int n = str1.length(), m = str2.length();
        string res(n + m - 1, '-');
        for(int i = 0; i < n; ++i) {
            if(str1[i] == 'T') {
                for(int j = 0; j < m; ++j)
                    res[i+j] = str2[j];
            }
        }
        string firstPassRes = res;
        for(int i = 0; i < n + m - 1; ++i)
            if(res[i] == '-')
                res[i] = 'a';
        for(int i = 0; i < n; ++i) {
            if(str1[i] == 'T') {
                for(int j = 0; j < m; ++j)
                    if(res[i+j] != str2[j])
                        return "";
            } else {
                bool isStringEqual = true;
                for(int j = 0; j < m; ++j)
                    if(res[i+j] != str2[j]) {
                        isStringEqual = false;
                        break;
                    }
                if(isStringEqual) {
                    int j = m-1;
                    for(; j >= 0; --j)
                        if(firstPassRes[i+j] == '-') {
                            if(str2[j] == 'a') {
                                res[i+j] = 'b';
                                break;
                            }
                        }
                    if(j == -1)
                        return "";
                }
            }
        }
        return res;
    }
};

// Explaination
/*
We first process the 'T' constraints, followed by the 'F' constraints.

We traverse all 'T' positions in str1 and fill str2 into the target string word. If a conflict occurs during this process, meaning a different character has already been assigned to the same position, then no valid solution exists, and we return an empty string. We also maintain a fixed array to record which positions are fixed by 'T' constraints.

Next, for all positions that are not fixed, we assign the character 'a' by default to ensure the lexicographically smallest result.

We then process the 'F' constraints. For each position i where str1[i]= ′F′, we check whether the substring word[i…i+m−1] is exactly equal to str2. If it is not equal, no action is needed. However, if it is equal, we must modify at least one non-fixed character within this window to break the match.

To maintain the smallest lexicographical order, we choose to modify the rightmost non-fixed character in the window, changing it to 'b'.

A natural concern is whether modifying the rightmost non-fixed character could invalidate a previously satisfied 'F' constraint. We now show that this cannot happen.

Suppose str1 contains two 'F' positions at indices i1 and i2. When processing i2, we modify a character in its window, which could potentially make the substring at i1 equal to str2, violating the 'F' constraint.

Consider str2 = A+′a′+B+′b'+C. 
At index i1, the substring is A+′a'+B+′a′+C, and at index i2, it is A+′a′+B+′b′+C. We modify the 'a' in the i2 window to 'b', which may affect the substring at i1.

Since the rightmost non-fixed character in the i2 window is the first 'a', there are no non-fixed characters to its right within the window. Also, the prefix B+′b′+C must match a prefix of str2 due to 'T' constraints.
The string A must be a suffix of A+′a′+B.

We now consider three cases based on the relative lengths of A and B:

Length of A equals length of B
    Since B+′b′+C is a prefix of str2=A+′a′+B+′b′+C, this implies 'b' = 'a', which is impossible.

Length of A is greater than length of B
    Since both A and B+′b′+C are prefixes of str2, let A=B+′b′+D.
    Because A is also a suffix of A+′a′+B, we obtain: B+′b′+D=D+′a′+B
    Removing common parts leads to 'b' = 'a', which is impossible.

Length of A is less than length of B
    Since A is a suffix of A+′a′+B, let B=D+A. 
    Since B+′b′+C is a prefix of str2, we obtain: (D+A)+′b′=A+′a′+D 
    Again, this leads to 'b' = 'a', which is impossible.

In all cases, we reach a contradiction. Therefore, modifying the rightmost non-fixed character will never violate any previously satisfied 'F' constraint, while also minimizing the lexicographical impact.
*/

// Another clean implementation
class Solution {
public:
    string generateString(string str1, string str2) {
        int n = str1.size(), m = str2.size();
        string s(n + m - 1, 'a');
        vector<int> fixed(n + m - 1, 0);
        for (int i = 0; i < n; i++) {
            if (str1[i] == 'T') {
                for (int j = i; j < i + m; j++) {
                    if (fixed[j] && s[j] != str2[j - i]) {
                        return "";
                    } else {
                        s[j] = str2[j - i];
                        fixed[j] = 1;
                    }
                }
            }
        }

        for (int i = 0; i < n; i++) {
            if (str1[i] == 'F') {
                bool flag = false;
                int idx = -1;
                for (int j = i + m - 1; j >= i; j--) {
                    if (str2[j - i] != s[j]) {
                        flag = true;
                    }
                    if (idx == -1 && !fixed[j]) {
                        idx = j;
                    }
                }
                if (flag) {
                    continue;
                } else if (idx != -1) {
                    s[idx] = 'b';
                } else {
                    return "";
                }
            }
        }
        return s;
    }
};
